<a href="https://colab.research.google.com/github/JoalissonAraujo/hidro-estacoes-ana/blob/main/untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/anagovbr/hidro-dados-estacoes-convencionais/main/Inventario_Estacoes_Hidrologicas_04-08-2023.csv"

df = pd.read_csv(url, sep=';', encoding='latin1')  # o arquivo usa ; e encoding latin1

print(df.head())

# 2. Renomear colunas para facilitar manipulação
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# 3. Mostrar as primeiras linhas e info básica
print("Primeiras linhas:")
print(df.head())

print("\nInformações gerais:")
print(df.info())

# 4. Verificar quantos valores faltantes por coluna
print("\nValores faltantes por coluna:")
print(df.isnull().sum())

# 5. Limpar: remover linhas com qualquer dado faltante
df_limpo = df.dropna()

print(f"\nApós limpeza, número de linhas: {len(df_limpo)}")

# 6. Resetar índice após limpeza
df_limpo = df_limpo.reset_index(drop=True)

# 7. Salvar CSV limpo localmente
df_limpo.to_csv('inventario_estacoes_limpo.csv', index=False)

print("\nArquivo CSV limpo salvo como 'inventario_estacoes_limpo.csv'")

<ipython-input-3-46bde9d061b1>:5: DtypeWarning: Columns (12,13,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, sep=';', encoding='latin1')  # o arquivo usa ; e encoding latin1

   ï»¿Codigo          Nome TipoEstacao CodigoAdicional  Latitude  Longitude  \
0      47000  SALINÃPOLIS         PLU           82144   -0.6500   -47.5500
1      47001     MARACANÃ         PLU             NaN   -0.8333   -47.5000
2      47002  SALINÃPOLIS         PLU             ANA   -0.6231   -47.3536
3      47003       CURUÃA         PLU             ANA   -0.7375   -47.8536
4      47004     PRIMAVERA         PLU             NaN   -0.9294   -47.0994

   Altitude  AreaDrenagem  BaciaCodigo                         BaciaNome  ...  \
0      14.0           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
1      68.0           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
2       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
3       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
4       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...

   PeriodoRegistradorChuvaInicio PeriodoRegistradorChuvaFim  \
0                     01/01/1923                 01/12/1964
1                            NaN                        NaN
2                     01/12/1977                 01/12/2013
3                     01/08/1987                 01/01/1999
4                            NaN                        NaN

  PeriodoTanqueEvapoInicio PeriodoTanqueEvapoFim  PeriodoClimatologicaInicio  \
0               01/01/1923            01/12/1964                  01/01/1923
1                      NaN                   NaN                         NaN
2               01/12/1977            01/10/2015                         NaN
3                      NaN                   NaN                         NaN
4                      NaN                   NaN                         NaN

  PeriodoClimatologicaFim  PeriodoPiezometriaInicio PeriodoPiezometriaFim  \
0              01/12/1964                       NaN                   NaN
1                     NaN                       NaN                   NaN
2                     NaN                       NaN                   NaN
3                     NaN                       NaN                   NaN
4                     NaN                       NaN                   NaN

   PeriodoTelemetricaInicio PeriodoTelemetricaFim
0                       NaN                   NaN
1                       NaN                   NaN
2                01/08/2010                   NaN
3                01/08/2010                   NaN
4                       NaN                   NaN

[5 rows x 58 columns]
Primeiras linhas:
   ï»¿codigo          nome tipoestacao codigoadicional  latitude  longitude  \
0      47000  SALINÃPOLIS         PLU           82144   -0.6500   -47.5500
1      47001     MARACANÃ         PLU             NaN   -0.8333   -47.5000
2      47002  SALINÃPOLIS         PLU             ANA   -0.6231   -47.3536
3      47003       CURUÃA         PLU             ANA   -0.7375   -47.8536
4      47004     PRIMAVERA         PLU             NaN   -0.9294   -47.0994

   altitude  areadrenagem  baciacodigo                         bacianome  ...  \
0      14.0           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
1      68.0           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
2       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
3       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...
4       NaN           NaN            3  ATLÃNTICO,TRECHO NORTE/NORDESTE  ...

   periodoregistradorchuvainicio periodoregistradorchuvafim  \
0                     01/01/1923                 01/12/1964
1                            NaN                        NaN
2                     01/12/1977                 01/12/2013
3                     01/08/1987                 01/01/1999
4                            NaN                        NaN

  periodotanqueevapoinicio periodotanqueevapofim  periodoclimatologicainicio  \
0               01/01/1923            01/12/1964                  01/01/1923
1                      NaN                   NaN                         NaN
2               01/12/1977            01/10/2015                         NaN
3                      NaN                   NaN                         NaN
4                      NaN                   NaN                         NaN

  periodoclimatologicafim  periodopiezometriainicio periodopiezometriafim  \
0              01/12/1964                       NaN                   NaN
1                     NaN                       NaN                   NaN
2                     NaN                       NaN                   NaN
3                     NaN                       NaN                   NaN
4                     NaN                       NaN                   NaN

   periodotelemetricainicio periodotelemetricafim
0                       NaN                   NaN
1                       NaN                   NaN
2                01/08/2010                   NaN
3                01/08/2010                   NaN
4                       NaN                   NaN

[5 rows x 58 columns]

Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37782 entries, 0 to 37781
Data columns (total 58 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ï»¿codigo                      37782 non-null  int64
 1   nome                           37782 non-null  object
 2   tipoestacao                    37782 non-null  object
 3   codigoadicional                18081 non-null  object
 4   latitude                       37782 non-null  float64
 5   longitude                      37782 non-null  float64
 6   altitude                       23680 non-null  float64
 7   areadrenagem                   12067 non-null  float64
 8   baciacodigo                    37782 non-null  int64
 9   bacianome                      37782 non-null  object
 10  subbaciacodigo                 37782 non-null  int64
 11  subbacianome                   37782 non-null  object
 12  riocodigo                      16329 non-null  object
 13  rionome                        16329 non-null  object
 14  estadocodigo                   37782 non-null  int64
 15  estadosigla                    37782 non-null  object
 16  municipiocodigo                37782 non-null  int64
 17  municipionome                  37782 non-null  object
 18  responsavelcodigo              37782 non-null  int64
 19  responsavelnome                37782 non-null  object
 20  operadoracodigo                37782 non-null  int64
 21  operadoranome                  37782 non-null  object
 22  responsavelunidade             12252 non-null  float64
 23  operadoraunidade               8982 non-null   float64
 24  operadorasubunidade            9258 non-null   float64
 25  tipoestacaoescala              37782 non-null  object
 26  tipoestacaoregistradornivel    37782 non-null  object
 27  tipoestacaodescliquida         37782 non-null  object
 28  tipoestacaosedimentos          37782 non-null  object
 29  tipoestacaoqualagua            37782 non-null  object
 30  tipoestacaopluviometro         37782 non-null  object
 31  tipoestacaoregistradorchuva    37782 non-null  object
 32  tipoestacaotanqueevapo         37782 non-null  object
 33  tipoestacaoclimatologica       37782 non-null  object
 34  tipoestacaopiezometria         37782 non-null  object
 35  tipoestacaotelemetrica         37782 non-null  object
 36  periodoescalainicio            11811 non-null  object
 37  periodoescalafim               5346 non-null   object
 38  periodoregistradornivelinicio  1049 non-null   object
 39  periodoregistradornivelfim     728 non-null    object
 40  periododescliquidainicio       8092 non-null   object
 41  periododescliquidafim          3596 non-null   object
 42  periodosedimentosinicio        2462 non-null   object
 43  periodosedimentosfim           551 non-null    object
 44  periodoqualaguainicio          7655 non-null   object
 45  periodoqualaguafim             1231 non-null   object
 46  periodopluviometroinicio       20804 non-null  object
 47  periodopluviometrofim          7554 non-null   object
 48  periodoregistradorchuvainicio  3539 non-null   object
 49  periodoregistradorchuvafim     1740 non-null   object
 50  periodotanqueevapoinicio       2062 non-null   object
 51  periodotanqueevapofim          1079 non-null   object
 52  periodoclimatologicainicio     1930 non-null   object
 53  periodoclimatologicafim        969 non-null    object
 54  periodopiezometriainicio       155 non-null    object
 55  periodopiezometriafim          78 non-null     object
 56  periodotelemetricainicio       11728 non-null  object
 57  periodotelemetricafim          1427 non-null   object
dtypes: float64(7), int64(7), object(44)
memory usage: 16.7+ MB
None

Valores faltantes por coluna:
ï»¿codigo                            0
nome                                 0
tipoestacao                          0
codigoadicional                  19701
latitude                             0
longitude                            0
altitude                         14102
areadrenagem                     25715
baciacodigo                          0
bacianome                            0
subbaciacodigo                       0
subbacianome                         0
riocodigo                        21453
rionome                          21453
estadocodigo                         0
estadosigla                          0
municipiocodigo                      0
municipionome                        0
responsavelcodigo                    0
responsavelnome                      0
operadoracodigo                      0
operadoranome                        0
responsavelunidade               25530
operadoraunidade                 28800
operadorasubunidade              28524
tipoestacaoescala                    0
tipoestacaoregistradornivel          0
tipoestacaodescliquida               0
tipoestacaosedimentos                0
tipoestacaoqualagua                  0
tipoestacaopluviometro               0
tipoestacaoregistradorchuva          0
tipoestacaotanqueevapo               0
tipoestacaoclimatologica             0
tipoestacaopiezometria               0
tipoestacaotelemetrica               0
periodoescalainicio              25971
periodoescalafim                 32436
periodoregistradornivelinicio    36733
periodoregistradornivelfim       37054
periododescliquidainicio         29690
periododescliquidafim            34186
periodosedimentosinicio          35320
periodosedimentosfim             37231
periodoqualaguainicio            30127
periodoqualaguafim               36551
periodopluviometroinicio         16978
periodopluviometrofim            30228
periodoregistradorchuvainicio    34243
periodoregistradorchuvafim       36042
periodotanqueevapoinicio         35720
periodotanqueevapofim            36703
periodoclimatologicainicio       35852
periodoclimatologicafim          36813
periodopiezometriainicio         37627
periodopiezometriafim            37704
periodotelemetricainicio         26054
periodotelemetricafim            36355
dtype: int64

Após limpeza, número de linhas: 0

Arquivo CSV limpo salvo como 'inventario_estacoes_limpo.csv'